// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
const List<String> routeNames = <String>[
  'fluttercandies://chatlist',
  'fluttercandies://gridview',
  'fluttercandies://listview',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'how to build layout(reverse=true) close to trailing when children are not full of viewport.'
  ///
  /// [name] : 'fluttercandies://chatlist'
  ///
  /// [routeName] : 'ChatList'
  ///
  /// [description] : 'how to build layout(reverse=true) close to trailing when children are not full of viewport.'
  static const String fluttercandiesChatlist = 'fluttercandies://chatlist';

  /// 'show no more/loadmore at trailing when children are not full of viewport.'
  ///
  /// [name] : 'fluttercandies://gridview'
  ///
  /// [routeName] : 'GridView'
  ///
  /// [description] : 'show no more/loadmore at trailing when children are not full of viewport.'
  static const String fluttercandiesGridview = 'fluttercandies://gridview';

  /// 'show no more item at trailing when children are not full of viewport.'
  ///
  /// [name] : 'fluttercandies://listview'
  ///
  /// [routeName] : 'ListView'
  ///
  /// [description] : 'show no more item at trailing when children are not full of viewport.'
  static const String fluttercandiesListview = 'fluttercandies://listview';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
