// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';
import 'pages/chat_list_demo.dart';
import 'pages/gridview_demo.dart';
import 'pages/listview_demo.dart';
import 'pages/main_page.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'fluttercandies://chatlist':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: ChatListDemo(),
        routeName: 'ChatList',
        description:
            'how to build layout(reverse=true) close to trailing when children are not full of viewport.',
      );
    case 'fluttercandies://gridview':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: GridViewDemo(),
        routeName: 'GridView',
        description:
            'show no more/loadmore at trailing when children are not full of viewport.',
      );
    case 'fluttercandies://listview':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: ListViewDemo(),
        routeName: 'ListView',
        description:
            'show no more item at trailing when children are not full of viewport.',
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: MainPage(),
        routeName: 'MainPage',
      );
    default:
      return const FFRouteSettings(name: '404', routeName: '404_page');
  }
}
